# https://leetcode.com/problems/find-the-difference/description/
# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        ls = self.countLetters(s)
        lt = self.countLetters(t)

        # find diff
        for c in lt:
            if c not in ls:
                return c
            if lt[c] - ls[c] > 0:
                return c
        return ""

    def countLetters(self, s):
        letters = {}
        for c in s:
            if c not in letters:
                letters[c] = 0
            else:
                letters[c] += 1
        return letters